// Mocks generated by Mockito 5.0.15 from annotations
// in pokedex_flutter/test/features/domain/usecases/get_all_pokemon_by_type/get_all_pokemon_by_type_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_flutter/core/error/failure.dart' as _i5;
import 'package:pokedex_flutter/features/pokedex/domain/entities/pokemon_entity.dart'
    as _i6;

import 'get_all_pokemon_by_type_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetAllPokemonByTypeSpy].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPokemonByTypeSpy extends _i1.Mock
    implements _i3.GetAllPokemonByTypeSpy {
  MockGetAllPokemonByTypeSpy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>> callSuccess(
          {String? name}) =>
      (super.noSuchMethod(Invocation.method(#callSuccess, [], {#name: name}),
          returnValue:
              Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PokemonEntity>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>> callFailed(
          {int? offset}) =>
      (super.noSuchMethod(Invocation.method(#callFailed, [], {#offset: offset}),
          returnValue:
              Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PokemonEntity>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>);
  @override
  String toString() => super.toString();
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>> call(
          {String? type}) =>
      (super.noSuchMethod(Invocation.method(#call, [], {#type: type}),
          returnValue:
              Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PokemonEntity>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>);
}
